# Numpy

# Creating Numpy Arrays

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [ ]:
#dtype
np.array([1,2,3],dtype='float')
np.array([1,2,3], dtype=bool)
np.array([1,2,3],dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones and np.zeros
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
np.random.random((3,4))

array([[0.08039836, 0.58015769, 0.01162141, 0.17732125],
       [0.90935083, 0.07601064, 0.39448413, 0.44649572],
       [0.34837086, 0.1820564 , 0.92600339, 0.5405772 ]])

In [ ]:
# np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
#ndim
a2.ndim

2

In [ ]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [ ]:
# size
a3.size

8

In [ ]:
# itemsize
a2.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#scalar operations
#arithmetic
a1*2
a1+2
a1-2
a1//2
a1/2
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations
# arithmetic
a1 + a2
a1 - a2
a1 / a2
a1 * a2


array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
# max/min/sum/prod
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[17., 10., 95.],
       [86., 11., 35.],
       [30.,  7., 47.]])

In [ ]:
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)

5277750555000.0

In [ ]:
# 0 -> col and 1 -> row
np.max(a1,axis=0)
np.min(a1,axis=0)

array([17.,  7., 35.])

In [ ]:
# mean/median/std/var
np.mean(a1,axis=0)
np.median(a1)
np.std(a1)
np.var(a1)

array([44.33333333,  9.33333333, 59.        ])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponential
np.log(a1)
np.exp(a1)

array([[2.41549528e+07, 2.20264658e+04, 1.81123908e+41],
       [2.23524660e+37, 5.98741417e+04, 1.58601345e+15],
       [1.06864746e+13, 1.09663316e+03, 2.58131289e+20]])

In [ ]:
# round/ floor/ ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[ 8., 89.,  3.],
       [89., 37., 86.]])

# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

9

In [ ]:
a1[0]

0

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

6

In [ ]:
a2[2,3]

11

In [ ]:
a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[0,1,0]

2

In [ ]:
a3[0,0,0]

0

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[[0,0,2,2],[0,3,0,3]]

array([ 0,  3,  8, 11])

In [ ]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1, :,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

# Numpy array vs Python lists

In [ ]:
# speed
# list
import time
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]
c=[]
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

3.708913803100586


In [ ]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000, 20000000)
start = time.time()
c = a + b
print(time.time() - start)

0.06488966941833496


In [ ]:
# memory
import sys
a = [i for i in range(10000000)]
sys.getsizeof(a)

89095160

In [ ]:
a = np.arange(10000000, dtype = np.int8)
sys.getsizeof(a)

10000112

In [ ]:
# convenience

# Advanced Indexing

In [ ]:
# Normal Indexing and slicing
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Fancy Indexing
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[56,  5, 84, 15],
       [12, 34, 13, 70],
       [30, 46, 19, 66],
       [47, 64, 50, 82],
       [34, 94, 30, 49],
       [47, 52,  2, 90]])

In [ ]:
# find all numbers greater than 50
a[a > 50]

array([56, 84, 70, 66, 64, 82, 94, 52, 90])

In [ ]:
# find all numbers greater than 50 and are even
a[(a > 50) & (a % 2 ==0)]

array([56, 84, 70, 66, 64, 82, 94, 52, 90])

In [ ]:
# find all the numbers not divisible by 7
a[~(a % 7 == 0)]

array([ 5, 15, 12, 34, 13, 30, 46, 19, 66, 47, 64, 50, 82, 34, 94, 30, 47,
       52,  2, 90])

# Broadcasting

In [ ]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a+b)

[[ 6  8 10]
 [12 14 16]]


In [ ]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)
print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [ ]:
# more examples
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
print(a)
print(b)
print(a+b)


[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)
print(a+b)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:
a = np.array([1])
b = np.arange(4).reshape(2,2)
print(a+b)

[[1 2]
 [3 4]]


In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

# Working with mathematical formulas

In [ ]:
a = np.arange(10)
np.sum(a)

45

In [ ]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# sigmoid
def sigmoid(array):
  return 1/(1+np.exp(-(array)))
a = np.arange(10)
sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [ ]:
# mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)
def mse(actual, predicted):
  return np.mean((actual - predicted)**2)
mse(actual, predicted)

556.24

In [ ]:
# binary cross entropy


# Working with missing values

In [ ]:
# working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [ ]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

# Plotting Graphs

In [ ]:

# plotting a 2D plot
# x=y
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = X

np.sort

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
np.sort(a)

array([ 4,  5,  6, 15, 25, 28, 29, 31, 36, 37, 50, 61, 72, 73, 97])

In [ ]:
b = np.random.randint()
np.sort()

np.append

In [2]:
# code
a

array([61, 97,  4, 31, 15, 72,  5, 25, 73, 28, 36,  6, 50, 37, 29])

In [3]:
np.append(a,200)

array([ 61,  97,   4,  31,  15,  72,   5,  25,  73,  28,  36,   6,  50,
        37,  29, 200])

In [5]:
b = np.random.randint(1,100,15).reshape(3,5)
b

array([[11, 54, 60, 44, 90],
       [18, 21, 98, 85, 13],
       [65,  5, 73, 98, 99]])

In [7]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[11., 54., 60., 44., 90.,  1.],
       [18., 21., 98., 85., 13.,  1.],
       [65.,  5., 73., 98., 99.,  1.]])

np.concatenate

In [8]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

In [11]:
e = np.array([1,1,2,2,3,3,4,4,5,5,5])
np.unique(e)

array([1, 2, 3, 4, 5])

np.expand_dims

In [14]:
b = np.expand_dims(a,axis=0)

In [15]:
b.shape

(1, 15)

np.where

In [16]:
np.where(a>50)

(array([0, 1, 5, 8]),)

In [17]:
# replace all values >50 with 0
np.where(a>50,0,a)

array([ 0,  0,  4, 31, 15,  0,  5, 25,  0, 28, 36,  6, 50, 37, 29])

In [18]:
np.where(a%2==0, 0,a)

array([61, 97,  0, 31, 15,  0,  5, 25, 73,  0,  0,  0,  0, 37, 29])

np.argmax

In [19]:
a

array([61, 97,  4, 31, 15, 72,  5, 25, 73, 28, 36,  6, 50, 37, 29])

In [20]:
np.argmax(a)

1

In [21]:
np.argmax(c)

5

np.argmin

In [22]:
np.argmin(a)

2

np.cumsum

In [23]:
np.cumsum(a)

array([ 61, 158, 162, 193, 208, 280, 285, 310, 383, 411, 447, 453, 503,
       540, 569])

np.cumprod

In [24]:
np.cumprod(a)

array([                 61,                5917,               23668,
                    733708,            11005620,           792404640,
                3962023200,         99050580000,       7230692340000,
           202459385520000,    7288537878720000,   43731227272320000,
       2186561363616000000, 7115794158953793536, 3443845798854944768])

np.percentile

In [25]:
np.percentile(a,100)

97.0

In [26]:
np.percentile(a,0)

4.0

In [27]:
np.median(a)

31.0

In [ ]:
np.histogram

In [29]:
a

array([61, 97,  4, 31, 15, 72,  5, 25, 73, 28, 36,  6, 50, 37, 29])

In [31]:
np.histogram(a,2)

(array([11,  4]), array([ 4. , 50.5, 97. ]))

np.corrcoef

In [34]:
e = np.array([3,2,7,8,9,1,3,4,5,7,9])

In [35]:
np.corrcoef(a,e)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 15 and the array at index 1 has size 11

np.isin

In [37]:
np.isin(a,[2,3,5])

array([5])

np.flip

In [38]:
np.flip(a)

array([29, 37, 50,  6, 36, 28, 73, 25,  5, 72, 15, 31,  4, 97, 61])

In [40]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
np.flip(c, axis=0)

array([[3, 4, 5],
       [0, 1, 2]])

np.put

In [43]:
np.put(a,[0,1],[110,65])

In [44]:
a

array([110,  65,   4,  31,  15,  72,   5,  25,  73,  28,  36,   6,  50,
        37,  29])

np.delete

In [46]:
np.delete(a,0)

array([65,  4, 31, 15, 72,  5, 25, 73, 28, 36,  6, 50, 37, 29])

In [47]:
np.delete(a,[0,1,2])

array([31, 15, 72,  5, 25, 73, 28, 36,  6, 50, 37, 29])

Set functions
1.  np.union1d
2.  np.intersect1d
1. np.setdiff1d
2.  np.setxor1d
1.  np.in1d







**-np.clip
-np.swaaxes
-np.uniform
-np.count_nonzero
-np.title
-np.repeat
-np.allclose and equals
**

In [48]:
# np.clip
np.clip(a,a_min=25,a_max=50)

array([50, 50, 25, 31, 25, 50, 25, 25, 50, 28, 36, 25, 50, 37, 29])