**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [3]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [ ]:
#Code here

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [ ]:
#Code here

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [ ]:
#Code here

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [ ]:
#Code here

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
#Code here

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [ ]:
#Code here

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [ ]:
#Code here

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
import numpy as np
a = np.arange(0,15,1).reshape(5,3)
b = np.arange(0,15,1).reshape(5,3)

def stacking(*arrays):
  if not all(isinstance(array, np.ndarray) for array in arrays):
    raise TypeError("All inputs must be Numpy arrays")



  return np.vstack((arrays))

stacking(a,b)




array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here
def date_array(start_date, end_date):
  start = np.datetime64(start_date)
  end = np.datetime64(end_date)
  date_range =  np.arange(start, end+np.timedelta64(1,'D'))
  return date_range.tolist()
date_array('2025-02-01','2025-02-12')


[datetime.date(2025, 2, 1),
 datetime.date(2025, 2, 2),
 datetime.date(2025, 2, 3),
 datetime.date(2025, 2, 4),
 datetime.date(2025, 2, 5),
 datetime.date(2025, 2, 6),
 datetime.date(2025, 2, 7),
 datetime.date(2025, 2, 8),
 datetime.date(2025, 2, 9),
 datetime.date(2025, 2, 10),
 datetime.date(2025, 2, 11),
 datetime.date(2025, 2, 12)]

###`Q-14:` Subtract the mean of each row from a matrix.

In [5]:
#code here
a = np.arange(0,15,1).reshape(3,5)
total_mean = 0
for row in a:
  total_mean+=np.mean(row)
a = a-total_mean
a

array([[-21., -20., -19., -18., -17.],
       [-16., -15., -14., -13., -12.],
       [-11., -10.,  -9.,  -8.,  -7.]])

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_means = np.mean(A, axis=1, keepdims = True)
result = A - row_means
print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [21]:
#Code here
a = np.arange(0,15,1).reshape(3,5)
print(a)
a[:,[1,2]]=a[:,[2,1]]
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  2  1  3  4]
 [ 5  7  6  8  9]
 [10 12 11 13 14]]


###`Q-16:` Replace odd elements in arrays with -1.

In [16]:
#Code here
print(a)
a[~(a%2==0)]=-1
print(a)

[[ 0  2  1  3  4]
 [ 5  7  6  8  9]
 [10 12 11 13 14]]
[[ 0  2 -1 -1  4]
 [-1 -1  6  8 -1]
 [10 12 -1 -1 14]]


In [22]:
print(a)
np.where(~(a%2==0),-1,a)

[[ 0  2  1  3  4]
 [ 5  7  6  8  9]
 [10 12 11 13 14]]


array([[ 0,  2, -1, -1,  4],
       [-1, -1,  6,  8, -1],
       [10, 12, -1, -1, 14]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [25]:
#Code here
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
c = np.vstack((a,b))
np.max(c,axis=0)

array([6, 3, 1, 7, 8])

In [26]:
# another way of doing this
np.maximum(a,b)

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [29]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[3427, 4961, 4399, 7470, 9705],
       [ 903,  272, 6205, 3702, 7084],
       [ 659, 7298, 5758, 5494, 1351],
       [2960, 9530, 1208,  861,  982],
       [5173, 2046, 4678, 5674,  959],
       [5733, 3404, 7865, 7174, 1242],
       [4227, 1252,   93,  986, 3178],
       [2874, 5936, 8594, 7699, 8246]])

In [31]:
#Code here
arr1[:,::2]

array([[3427, 4399, 9705],
       [ 903, 6205, 7084],
       [ 659, 5758, 1351],
       [2960, 1208,  982],
       [5173, 4678,  959],
       [5733, 7865, 1242],
       [4227,   93, 3178],
       [2874, 8594, 8246]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [33]:
#Code here
def nlargestitem(arr, n):
  if n<=len(arr):
    return np.sort(arr)[::-1][n-1]
nlargestitem([1,5,32,76,86,96],1)
nlargestitem([1,5,32,76,86,96],2)


86

In [ ]:
#another way of doing this faster way for larger arrays

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here
a = np.array([1,2,3])
array = np.array([])
for element in a:
  for i in range(0,3):
   array = np.append(array,element)
for i in range(0,3):
  for element in a:
    array = np.append(array,element)
array.astype(int)


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [41]:
#another way of doing this
a = np.array([1,2,3])
np.append(np.repeat(a,3), np.tile(a,3))



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])